
import random

superhero_list = [
        {   "id":   "5",   "name": "Abomination"  },
        {   "id":   "6",   "name": "Abraxas"  },
        {   "id":  "11",   "name": "Agent Zero"  },
        {   "id":  "12",   "name": "Air-Walker"  },
        {   "id":  "15",   "name": "Alfred Pennyworth"  },
        {   "id":  "17",   "name": "Amazo"  },
        {   "id":  "18",   "name": "Ammo"  },
        {   "id":  "20",   "name": "Angel"  },
        {   "id":  "23",   "name": "Animal Man"  },
        {   "id":  "24",   "name": "Annihilus"  },
        {   "id":  "25",   "name": "Ant-Man"  },
        {   "id":  "26",   "name": "Anti-Monitor"  },
        {   "id":  "27",   "name": "Anti-Spawn"  },
        {   "id":  "28",   "name": "Anti-Venom"  },
        {   "id":  "29",   "name": "Apocalypse"  },
        {   "id":  "30",   "name": "Aquababy"  },
        {   "id":  "31",   "name": "Aqualad"  },
        {   "id":  "32",   "name": "Aquaman"  },
        {   "id":  "33",   "name": "Arachne"  },
        {   "id":  "34",   "name": "Archangel"  },
        {   "id":  "36",   "name": "Ares"  },
        {   "id":  "39",   "name": "Arsenal"  },
        {   "id":  "40",   "name": "Astro Boy"  },
        {   "id":  "41",   "name": "Atlas"  },
        {   "id":  "42",   "name": "Atom"  },
        {   "id":  "43",   "name": "Atom Girl"  },
        {   "id":  "44",   "name": "Aurora"  },
        {   "id":  "45",   "name": "Azazel"  },
        {   "id":  "46",   "name": "Azrael"  },
        {   "id":  "47",   "name": "Aztar"  },
        {   "id":  "48",   "name": "Bane"  },
        {   "id":  "49",   "name": "Banshee"  },
        {   "id":  "51",   "name": "Batgirl"  },
        {   "id":  "52",   "name": "Batman"  },
        {   "id":  "53",   "name": "Battlestar"  },
        {   "id":  "55",   "name": "Beast"  },
        {   "id":  "56",   "name": "Beast Boy"  },
        {   "id":  "57",   "name": "Beetle"  },
        {   "id":  "61",   "name": "Beyonder"  },
        {   "id":  "67",   "name": "Binary"  },
        {   "id":  "69",   "name": "Birdman"  },
        {   "id":  "70",   "name": "Bishop"  },
        {   "id":  "71",   "name": "Bizarro"  },
        {   "id":  "73",   "name": "Black Adam"  },
        {   "id":  "75",   "name": "Black Canary"  },
        {   "id":  "76",   "name": "Black Cat"  },
        {   "id":  "77",   "name": "Black Goliath"  },
        {   "id":  "82",   "name": "Black Widow"  },
        {   "id":  "83",   "name": "Blackout"  },
        {   "id":  "84",   "name": "Blackwing"  },
        {   "id":  "85",   "name": "Blackwulf"  },
        {   "id":  "86",   "name": "Blade"  },
        {   "id":  "89",   "name": "Blink"  },
        {   "id":  "90",   "name": "Blizzard"  },
        {   "id":  "91",   "name": "Blob"  },
        {   "id":  "93",   "name": "Bloodhawk"  },
        {   "id":  "94",   "name": "Bloodwraith"  },
        {   "id":  "95",   "name": "Blue Beetle"  },
        {   "id":  "96",   "name": "Bolt"  },
        {   "id":  "99",   "name": "Boomer"  },
        {   "id": "100",   "name": "Booster Gold"  },
        {   "id": "102",   "name": "Brainiac"  },
        {   "id": "104",   "name": "Bullseye"  },
        {   "id": "105",   "name": "Bumblebee"  },
        {   "id": "106",   "name": "Bumbleboy"  },
        {   "id": "108",   "name": "Cable"  },
        {   "id": "109",   "name": "Callisto"  },
        {   "id": "112",   "name": "Captain America"  },
        {   "id": "113",   "name": "Captain Atom"  },
        {   "id": "114",   "name": "Captain Britain"  },
        {   "id": "117",   "name": "Captain Planet"  },
        {   "id": "119",   "name": "Carnage"  },
        {   "id": "122",   "name": "Catwoman"  },
        {   "id": "125",   "name": "Cerebra"  },
        {   "id": "127",   "name": "Chameleon"  },
        {   "id": "128",   "name": "Changeling"  },
        {   "id": "129",   "name": "Cheetah"  },
        {   "id": "130",   "name": "Chromos"  },
        {   "id": "131",   "name": "Chuck Norris"  },
        {   "id": "134",   "name": "Cloak"  },
        {   "id": "137",   "name": "Colossal Boy"  },
        {   "id": "138",   "name": "Colossus"  },
        {   "id": "139",   "name": "Corsair"  },
        {   "id": "140",   "name": "Crimson Crusader"  },
        {   "id": "141",   "name": "Crimson Dynamo"  },
        {   "id": "145",   "name": "Cyborg"  },
        {   "id": "147",   "name": "Cyclops"  },
        {   "id": "148",   "name": "Cypher"  },
        {   "id": "149",   "name": "Dagger"  },
        {   "id": "152",   "name": "Daredevil"  },
        {   "id": "153",   "name": "Darkhawk"  },
        {   "id": "154",   "name": "Darkman"  },
        {   "id": "155",   "name": "Darkside"  },
        {   "id": "156",   "name": "Darkstar"  },
        {   "id": "157",   "name": "Dash"  },
        {   "id": "158",   "name": "Dazzler"  },
        {   "id": "159",   "name": "Deadman"  },
        {   "id": "160",   "name": "Deadpool"  },
        {   "id": "161",   "name": "Deadshot"  },
        {   "id": "162",   "name": "Deathlok"  },
        {   "id": "163",   "name": "Deathstroke"  },
        {   "id": "168",   "name": "Doctor Doom"  },
        {   "id": "169",   "name": "Doctor Fate"  },
        {   "id": "170",   "name": "Doctor Octopus"  },
        {   "id": "171",   "name": "Doctor Strange"  },
        {   "id": "172",   "name": "Domino"  },
        {   "id": "174",   "name": "Doomsday"  },
        {   "id": "175",   "name": "Doppelganger"  },
        {   "id": "177",   "name": "Dr Manhattan"  },
        {   "id": "178",   "name": "Ego"  },
        {   "id": "179",   "name": "Elastigirl"  },
        {   "id": "180",   "name": "Electro"  },
        {   "id": "181",   "name": "Elektra"  },
        {   "id": "183",   "name": "Elongated Man"  },
        {   "id": "188",   "name": "Exodus"  },
        {   "id": "190",   "name": "Falcon"  },
        {   "id": "196",   "name": "Firebird"  },
        {   "id": "197",   "name": "Firelord"  },
        {   "id": "198",   "name": "Firestar"  },
        {   "id": "199",   "name": "Firestorm"  },
        {   "id": "200",   "name": "Fixer"  },
        {   "id": "201",   "name": "Flash Gordon"  },
        {   "id": "202",   "name": "Flash"  },
        {   "id": "206",   "name": "Frenzy"  },
        {   "id": "207",   "name": "Frigga"  },
        {   "id": "208",   "name": "Galactus"  },
        {   "id": "209",   "name": "Gambit"  },
        {   "id": "210",   "name": "Garbage Man"  },
        {   "id": "212",   "name": "General Zod"  },
        {   "id": "213",   "name": "Genesis"  },
        {   "id": "214",   "name": "Ghost Rider"  },
        {   "id": "216",   "name": "Giant-Man"  },
        {   "id": "217",   "name": "Giganta"  },
        {   "id": "218",   "name": "Goblin Queen"  },
        {   "id": "219",   "name": "Gog"  },
        {   "id": "221",   "name": "Goliath"  },
        {   "id": "222",   "name": "Granny Goodness"  },
        {   "id": "224",   "name": "Green Arrow"  },
        {   "id": "225",   "name": "Green Goblin"  },
        {   "id": "226",   "name": "Groot"  },
        {   "id": "227",   "name": "Guardian"  },
        {   "id": "230",   "name": "Hancock"  },
        {   "id": "231",   "name": "Harley Quinn"  },
        {   "id": "232",   "name": "Havok"  },
        {   "id": "234",   "name": "Hawkeye"  },
        {   "id": "235",   "name": "Hawkgirl"  },
        {   "id": "236",   "name": "Hawkman"  },
        {   "id": "237",   "name": "Hawkwoman"  },
        {   "id": "238",   "name": "Hellboy"  },
        {   "id": "239",   "name": "Hellcat"  },
        {   "id": "240",   "name": "Hellstorm"  },
        {   "id": "241",   "name": "Hercules"  },
        {   "id": "243",   "name": "Hit-Girl"  },
        {   "id": "244",   "name": "Hobgoblin"  },
        {   "id": "245",   "name": "Hollow"  },
        {   "id": "248",   "name": "Hulk"  },
        {   "id": "249",   "name": "Human Torch"  },
        {   "id": "250",   "name": "Huntress"  },
        {   "id": "251",   "name": "Husk"  },
        {   "id": "252",   "name": "Hydro-Man"  },
        {   "id": "253",   "name": "Hyperion"  },
        {   "id": "254",   "name": "Iceman"  },
        {   "id": "255",   "name": "Impulse"  },
        {   "id": "256",   "name": "Ink"  },
        {   "id": "257",   "name": "Invisible Woman"  },
        {   "id": "258",   "name": "Iron Fist"  },
        {   "id": "260",   "name": "Iron Monger"  },
        {   "id": "261",   "name": "Ironman"  },
        {   "id": "262",   "name": "Isis"  },
        {   "id": "266",   "name": "Jean Grey"  },
        {   "id": "269",   "name": "Jigsaw"  },
        {   "id": "275",   "name": "Joker"  },
        {   "id": "276",   "name": "Jolt"  },
        {   "id": "277",   "name": "Jubilee"  },
        {   "id": "278",   "name": "Juggernaut"  },
        {   "id": "279",   "name": "Junkpile"  },
        {   "id": "280",   "name": "Justice"  },
        {   "id": "281",   "name": "Kang"  },
        {   "id": "284",   "name": "Kid Flash"  },
        {   "id": "285",   "name": "Killer Croc"  },
        {   "id": "287",   "name": "Kingpin"  },
        {   "id": "288",   "name": "Klaw"  },
        {   "id": "291",   "name": "Kraven the Hunter"  },
        {   "id": "292",   "name": "Krypto"  },
        {   "id": "293",   "name": "Lady Bullseye"  },
        {   "id": "294",   "name": "Lady Deathstrike"  },
        {   "id": "296",   "name": "Leech"  },
        {   "id": "297",   "name": "Lex Luthor"  },
        {   "id": "298",   "name": "Light Lass"  },
        {   "id": "299",   "name": "Lightning Lad"  },
        {   "id": "300",   "name": "Lightning Lord"  },
        {   "id": "301",   "name": "Living Brain"  },
        {   "id": "304",   "name": "Lobo"  },
        {   "id": "305",   "name": "Loki"  },
        {   "id": "306",   "name": "Longshot"  },
        {   "id": "309",   "name": "Luna"  },
        {   "id": "313",   "name": "Magneto"  },
        {   "id": "314",   "name": "Magog"  },
        {   "id": "315",   "name": "Magus"  },
        {   "id": "319",   "name": "Mandarin"  },
        {   "id": "320",   "name": "Martian Manhunter"  },
        {   "id": "324",   "name": "Match"  },
        {   "id": "326",   "name": "Maverick"  },
        {   "id": "327",   "name": "Maxima"  },
        {   "id": "329",   "name": "Medusa"  },
        {   "id": "330",   "name": "Meltdown"  },
        {   "id": "331",   "name": "Mephisto"  },
        {   "id": "333",   "name": "Metallo"  },
        {   "id": "334",   "name": "Metamorpho"  },
        {   "id": "335",   "name": "Meteorite"  },
        {   "id": "336",   "name": "Metron"  },
        {   "id": "338",   "name": "Micro Lad"  },
        {   "id": "339",   "name": "Mimic"  },
        {   "id": "341",   "name": "Misfit"  },
        {   "id": "342",   "name": "Miss Martian"  },
        {   "id": "344",   "name": "Mister Freeze"  },
        {   "id": "349",   "name": "Moloch"  },
        {   "id": "350",   "name": "Molten Man"  },
        {   "id": "351",   "name": "Monarch"  },
        {   "id": "353",   "name": "Moon Knight"  },
        {   "id": "354",   "name": "Moonstone"  },
        {   "id": "356",   "name": "Morph"  },
        {   "id": "358",   "name": "Mr Incredible"  },
        {   "id": "361",   "name": "Mysterio"  },
        {   "id": "362",   "name": "Mystique"  },
        {   "id": "365",   "name": "Namorita"  },
        {   "id": "368",   "name": "Nick Fury"  },
        {   "id": "369",   "name": "Nightcrawler"  },
        {   "id": "370",   "name": "Nightwing"  },
        {   "id": "373",   "name": "Nite Owl"  },
        {   "id": "374",   "name": "Northstar"  },
        {   "id": "375",   "name": "Nova"  },
        {   "id": "377",   "name": "Offspring"  },
        {   "id": "378",   "name": "Omega Red"  },
        {   "id": "379",   "name": "Omniscient"  },
        {   "id": "380",   "name": "Onslaught"  },
        {   "id": "381",   "name": "Osiris"  },
        {   "id": "384",   "name": "Penguin"  },
        {   "id": "386",   "name": "Phantom"  },
        {   "id": "387",   "name": "Phantom Girl"  },
        {   "id": "388",   "name": "Phoenix"  },
        {   "id": "389",   "name": "Plastic Lad"  },
        {   "id": "390",   "name": "Plastic Man"  },
        {   "id": "391",   "name": "Plastique"  },
        {   "id": "392",   "name": "Poison Ivy"  },
        {   "id": "393",   "name": "Power Girl"  },
        {   "id": "394",   "name": "Power Man"  },
        {   "id": "397",   "name": "Psylocke"  },
        {   "id": "398",   "name": "Punisher"  },
        {   "id": "399",   "name": "Pyro"  },
        {   "id": "400",   "name": "Quantum"  },
        {   "id": "551",   "name": "Quailman"  },
        {   "id": "401",   "name": "Question"  },
        {   "id": "402",   "name": "Quicksilver"  },
        {   "id": "403",   "name": "Quill"  },
        {   "id": "406",   "name": "Raven"  },
        {   "id": "408",   "name": "Red Arrow"  },
        {   "id": "409",   "name": "Red Hood"  },
        {   "id": "410",   "name": "Red Hulk"  },
        {   "id": "411",   "name": "Red Mist"  },
        {   "id": "413",   "name": "Red Skull"  },
        {   "id": "414",   "name": "Red Tornado"  },
        {   "id": "415",   "name": "Redeemer"  },
        {   "id": "418",   "name": "Rick Flag"  },
        {   "id": "419",   "name": "Riddler"  },
        {   "id": "420",   "name": "Ripcord"  },
        {   "id": "421",   "name": "Robin"  },
        {   "id": "422",   "name": "Rocket Raccoon"  },
        {   "id": "423",   "name": "Rogue"  },
        {   "id": "424",   "name": "Ronin"  },
        {   "id": "425",   "name": "Rorschach"  },
        {   "id": "426",   "name": "Sabretooth"  },
        {   "id": "427",   "name": "Sage"  },
        {   "id": "428",   "name": "Sandman"  },
        {   "id": "429",   "name": "Sasquatch"  },
        {   "id": "431",   "name": "Scarecrow"  },
        {   "id": "432",   "name": "Scarlet Spider"  },
        {   "id": "433",   "name": "Scarlet Witch"  },
        {   "id": "435",   "name": "Scorpion"  },
        {   "id": "436",   "name": "Sentry"  },
        {   "id": "437",   "name": "Shadow King"  },
        {   "id": "438",   "name": "Shadowcat"  },
        {   "id": "440",   "name": "Shatterstar"  },
        {   "id": "441",   "name": "She-Hulk"  },
        {   "id": "442",   "name": "She-Thing"  },
        {   "id": "444",   "name": "Shriek"  },
        {   "id": "445",   "name": "Shrinking Violet"  },
        {   "id": "446",   "name": "Sif"  },
        {   "id": "447",   "name": "Silk Spectre"  },
        {   "id": "448",   "name": "Silver Surfer"  },
        {   "id": "449",   "name": "Silverclaw"  },
        {   "id": "450",   "name": "Sinestro"  },
        {   "id": "451",   "name": "Siren"  },
        {   "id": "455",   "name": "Sobek"  },
        {   "id": "456",   "name": "Solomon Grundy"  },
        {   "id": "457",   "name": "Songbird"  },
        {   "id": "458",   "name": "Space Ghost"  },
        {   "id": "459",   "name": "Spawn"  },
        {   "id": "460",   "name": "Spectre"  },
        {   "id": "462",   "name": "Speedy"  },
        {   "id": "467",   "name": "Spiderman"  },
        {   "id": "468",   "name": "Spyke"  },
        {   "id": "470",   "name": "Stardust"  },
        {   "id": "471",   "name": "Starfire"  },
        {   "id": "472",   "name": "Stargirl"  },
        {   "id": "475",   "name": "Storm"  },
        {   "id": "476",   "name": "Sub-Mariner"  },
        {   "id": "477",   "name": "Sunspot"  },
        {   "id": "479",   "name": "Superboy"  },
        {   "id": "481",   "name": "Supergirl"  },
        {   "id": "482",   "name": "Superman"  },
        {   "id": "483",   "name": "Swamp Thing"  },
        {   "id": "485",   "name": "Synch"  },
        {   "id": "486",   "name": "Tempest"  },
        {   "id": "487",   "name": "Thanos"  },
        {   "id": "489",   "name": "The Comedian"  },
        {   "id": "490",   "name": "Thing"  },
        {   "id": "491",   "name": "Thor"  },
        {   "id": "493",   "name": "Thunderbird"  },
        {   "id": "496",   "name": "Thunderstrike"  },
        {   "id": "497",   "name": "Thundra"  },
        {   "id": "499",   "name": "Tigra"  },
        {   "id": "500",   "name": "Tinkerer"  },
        {   "id": "501",   "name": "Titan"  },
        {   "id": "502",   "name": "Toad"  },
        {   "id": "503",   "name": "Toxin"  },
        {   "id": "505",   "name": "Trickster"  },
        {   "id": "507",   "name": "Two-Face"  },
        {   "id": "508",   "name": "Ultragirl"  },
        {   "id": "509",   "name": "Ultron"  },
        {   "id": "511",   "name": "Vagabond"  },
        {   "id": "513",   "name": "Valkyrie"  },
        {   "id": "514",   "name": "Vanisher"  },
        {   "id": "515",   "name": "Venom"  },
        {   "id": "516",   "name": "Vertigo"  },
        {   "id": "517",   "name": "Vindicator"  },
        {   "id": "520",   "name": "Vision"  },
        {   "id": "521",   "name": "Vulcan"  },
        {   "id": "522",   "name": "Vulture"  },
        {   "id": "524",   "name": "War Machine"  },
        {   "id": "525",   "name": "Warbird"  },
        {   "id": "526",   "name": "Warlock"  },
        {   "id": "527",   "name": "Warp"  },
        {   "id": "528",   "name": "Warpath"  },
        {   "id": "529",   "name": "Wasp"  },
        {   "id": "530",   "name": "Watcher"  },
        {   "id": "533",   "name": "Wildfire"  },
        {   "id": "536",   "name": "Wiz Kid"  },
        {   "id": "537",   "name": "Wolfsbane"  },
        {   "id": "538",   "name": "Wolverine"  },
        {   "id": "542",   "name": "Wondra"  },
        {   "id": "546",   "name": "Yellow Claw"  },
        {   "id": "547",   "name": "Yellowjacket"  },
        {   "id": "549",   "name": "Zatanna"  },
        {   "id": "550",   "name": "Zoom"  }
        ];

output_list = []

for index in range(170):
    selection = random.choice(superhero_list)
    superhero_list.remove(selection)
    output_list.append(selection)

import pprint
pprint.pprint(output_list)

